#ifndef SRC_ALGORITHM_SOLVER_SOLVER_TYPE_HPP_
#define SRC_ALGORITHM_SOLVER_SOLVER_TYPE_HPP_

namespace cgzr {

enum class SolverType { CONVEX_HULL = 0, LINE_SEGMENT_INTERSECTION };

}

#endif  // SRC_ALGORITHM_SOLVER_SOLVER_TYPE_HPP_
