#ifndef __VISUALIZATION_DRAWABLE_DRAWABLE_TYPE__HPP__
#define __VISUALIZATION_DRAWABLE_DRAWABLE_TYPE__HPP__

namespace cgzr {
enum class DrawableType { POINT_SET, LINE_STRING, UNSUPPORTED };
}

#endif /* __VISUALIZATION_DRAWABLE_DRAWABLE_TYPE__HPP__ */
